### ISSUE TITLE
Vorlauf Soll wird nach ca 10 stunden nicht mehr gepublisht

### ISSUE THREAD

**Issue by weberol** [Fellfalla/Thermoberry#12]
## How to reproduce 
??

## Actual Behavior
* Die MQTT Nachricht heizkreis/vorlauf_soll kommt nicht an, obwohl das Heizungsmodul läuft.
* thermoberry-heating-circuit.service meldet keine Auffälligkeiten

## Possible Reasons 
??

* `systemctl status thermoberry-heating-circuit.service`
```console
[2021-01-12 14:03:16,962][HeatingControl][INFO] - Setting loglevel to INFO
[2021-01-12 14:03:16,990][HeatingControl][INFO] - Connecting to MQTT broker...
[2021-01-12 14:03:17,420][HeatingControl][INFO] - Connection to MQTT broker: OK
[2021-01-12 14:03:17,571][HeatingControl][INFO] - Enabling automatic mode of heizkreis/steuerung
[2021-01-12 14:03:22,660][HeatingControl][ERROR] - 'sensors/heizkreis/1'
Traceback (most recent call last):
  File "heating_circuit.py", line 122, in update_heating_state
    if self.topic_states[self.topic_supplier_temperature] < \
KeyError: 'sensors/heizkreis/1'
[2021-01-12 14:03:27,685][HeatingControl][ERROR] - 'sensors/heizkreis/1'
Traceback (most recent call last):
  File "heating_circuit.py", line 122, in update_heating_state
    if self.topic_states[self.topic_supplier_temperature] < \
KeyError: 'sensors/heizkreis/1'

```

## Possible Solutions
* Vielleicht war automatik modus aus?

**Comment by Fellfalla** [comment]
Similar problems may appear with the mixer-module and sensor-module.
Try making the client more resilient: 

https://www.hivemq.com/blog/are-your-mqtt-applications-resilient-enough/
